server:
  port: 8081
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.19.128:3306/shop-product?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.19.128:8848

  jpa:
    properties:
      hibernate:
        # 自动根据实体创建表结构
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
